=== gabriellett/guteDAO/res/guteDAO.dtd
<!ELEMENT guteDAO (procedure+)>
<!ELEMENT procedure (sql+)>
<!ELEMENT sql (sql-data,param*,requires*)>
<!ELEMENT param EMPTY>
<!ELEMENT requires EMPTY>
<!ELEMENT sql-data (#PCDATA)>
<!ATTLIST guteDAO 
	logic-element CDATA #REQUIRED>
<!ATTLIST procedure
	type (update|query) #REQUIRED
	name CDATA #REQUIRED
>
<!ATTLIST sql
	name CDATA #REQUIRED
	required (true|false) #REQUIRED
>
<!ATTLIST param 
	name CDATA #REQUIRED
 	type (VARCHAR|NUMBER|TIMESTAMP|SEQUENCE) #REQUIRED
 >
<!ATTLIST requires 
	qryName CDATA #REQUIRED
 >

=== gabriellett/guteDAO/res/guteDAO_test.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE guteDAO SYSTEM "guteDAO.dtd">
<guteDAO logic-element="usuarios">


<procedure type="query" name="selectUsers">
	<sql name="qryPrincipal" required="true">
		<sql-data>
			SELECT * FROM USUARIOS
		</sql-data>
	</sql>
	
	<sql name="where" required="false">
		<sql-data>
			WHERE
		</sql-data>
		<requires qryName="qryPrincipal"/>
	</sql>
	
	<sql name="filterUser" required="false">
		<sql-data>
			ID_USUARIO = ?
		</sql-data>
		<param name="ID_USUARIO" type="NUMBER"/>
		<requires qryName="where"/>
	</sql>
</procedure>

</guteDAO>
